### Import Libraries

In [1]:
import pandas as pd
import numpy as np
import datetime as dt

In [2]:
# Define number of samples for each feature vector
m_samples = 100

#### Generate numeric columns

In [3]:
numeric_1 = 1200 * np.random.random(size=(m_samples,1))
numeric_1 = pd.Series(numeric_1.flatten())

In [4]:
numeric_2 = m_samples * np.random.random(size=(m_samples,1))
numeric_2 = pd.Series(numeric_2.flatten())

In [5]:
numeric_3 = m_samples * np.random.random(size=(m_samples,1))
numeric_3 = pd.Series(numeric_3.flatten())

##### Add NaNs to `numeric_2` and `numeric_3`

In [6]:
random_ints = np.random.random(size=m_samples).flatten()

In [7]:
numeric_2.loc[random_ints < 0.4] = np.nan

In [8]:
random_ints = np.random.random(size=m_samples).flatten()
numeric_3.loc[random_ints < 0.9] = np.nan

#### Generate datetime columns

In [9]:
datetimes_1 = pd.date_range(dt.datetime.now(), periods=m_samples, freq='1703587S')
datetimes_1 = pd.Series(datetimes_1).sample(frac=1)
datetimes_1 = datetimes_1.reset_index().drop('index', axis=1)

In [10]:
datetime = dt.datetime(year=2000, month=3, day=21, hour=22, minute=2, second=23)
datetimes_2 = pd.date_range(datetime, periods=m_samples, freq='30173587S')
datetimes_2 = pd.Series(datetimes_2).sample(frac=1)
datetimes_2 = datetimes_2.reset_index().drop('index', axis=1)

In [11]:
datetimes_1.iloc[0,0].weekday()

0

#### Generate boolean-like columns

In [12]:
# Generate array of random ints from 0 to 1
random_ints = np.random.random(size=m_samples).flatten()

# Initialise Series
boolean_like = pd.Series(random_ints)

# Assign str True and False values to 
boolean_like[random_ints >= 0.5] = 'True'
boolean_like[random_ints < 0.5] = 'False'

In [13]:
# Generate array of random ints from 0 to 1
random_ints = np.random.random(size=m_samples).flatten()

# Initialise Series
boolean_like_2 = pd.Series(random_ints)

# Assign str True and False values to 
boolean_like_2[random_ints >= 0.5] = 'true'
boolean_like_2[random_ints < 0.5] = 'false'

In [14]:
# Generate array of random ints from 0 to 1
random_ints = np.random.random(size=m_samples).flatten()

# Initialise Series
boolean_like_3 = pd.Series(random_ints)

# Assign str True and False values to 
boolean_like_3[random_ints >= 0.5] = 'TRUE'
boolean_like_3[random_ints < 0.5] = 'FALSE'

In [15]:
# Generate array of random ints from 0 to 1
random_ints = np.random.random(size=m_samples).flatten()

# Initialise Series
boolean_like_4 = pd.Series(random_ints)

# Assign str True and False values to 
boolean_like_4[random_ints >= 0.5] = 'TRUE'
boolean_like_4[random_ints < 0.5] = 'False'
boolean_like_4[random_ints >= 0.8] = 'True'

#### Generate true Boolean column

In [16]:
# Generate array of random ints from 0 to 1
random_ints = np.random.random(size=m_samples).flatten()

# Initialise Series
boolean = pd.Series(random_ints)

# Assign str True and False values to 
boolean[random_ints >= 0.5] = True
boolean[random_ints < 0.5] = False

#### Generate nominal column

In [18]:
# Generate array of random ints from 0 to 1
random_ints = np.random.random(size=m_samples).flatten()

# Initialise Series
nominal = pd.Series(random_ints)

# Assign str True and False values to 
nominal[random_ints >= 0.2] = 'Mouse'
nominal[random_ints > 0.4] = 'Cat'
nominal[random_ints < 0.2] = 'Dog'
nominal[random_ints > 0.8] = 'Iguana'

#### Generate ordinal column

In [19]:
# Generate array of random ints from 0 to 1
random_ints = np.random.random(size=m_samples).flatten()

# Initialise Series
ordinal_1 = pd.Series(random_ints)

In [20]:
ordinal_1[random_ints > 0] = 'strongly disagree'
ordinal_1[random_ints > 0.2] = 'disagree'
ordinal_1[random_ints > 0.4] = 'neither agree nor disagree'
ordinal_1[random_ints > 0.6] = 'agree'
ordinal_1[random_ints > 0.8] = 'strongly agree'

### Stitch together final dataframe

In [21]:
# Initialise final dataframe
df = pd.DataFrame(index=datetimes_1.index)

# Add datetime features
df['datetimes_1'] = datetimes_1
df['datetimes_2'] = datetimes_2

# Add numeric features
df['numeric_1'] = numeric_1
df['numeric_2'] = numeric_2
df['numeric_3'] = numeric_3

In [22]:
# Add Boolean-like features
df['boolean_like_1'] = boolean_like
df['boolean_like_2'] = boolean_like_2
df['boolean_like_3'] = boolean_like_3
df['boolean_like_4'] = boolean_like_4

In [23]:
# Add true Boolean features
df['boolean'] = boolean

In [24]:
# Add nominal features
df['nominal'] = nominal

In [25]:
# Add ordinal features
df['ordinal_1'] = ordinal_1

### Save to current directory

In [26]:
df.to_csv(path_or_buf='dataset_test.csv')

In [27]:
df

,datetimes_1,datetimes_2,numeric_1,numeric_2,numeric_3,boolean_like_1,boolean_like_2,boolean_like_3,boolean_like_4,boolean,nominal,ordinal_1
0,2022-12-05 00:00:19.201864,2060-06-16 11:48:44,1085.363773,NaN,NaN,False,true,FALSE,False,False,Mouse,neither agree nor disagree
1,2019-11-07 02:32:40.201864,2014-07-25 09:19:08,924.379152,42.915310,NaN,False,false,TRUE,TRUE,True,Mouse,strongly disagree
2,2019-07-31 12:27:05.201864,2055-09-05 08:03:09,566.488961,34.995786,NaN,True,true,FALSE,TRUE,True,Dog,disagree
3,2023-07-29 14:37:43.201864,2090-02-05 15:55:21,822.036241,NaN,18.199072,True,false,TRUE,TRUE,False,Cat,strongly agree
4,2020-08-09 03:36:18.201864,2087-03-25 23:16:00,679.786375,NaN,NaN,False,false,TRUE,TRUE,True,Iguana,strongly disagree
5,2023-11-24 21:56:25.201864,2045-02-27 18:58:52,575.920156,18.179089,NaN,True,false,FALSE,True,False,Dog,strongly disagree
6,2019-09-28 16:06:26.201864,2046-02-12 00:31:59,268.480528,NaN,NaN,True,true,TRUE,TRUE,True,Iguana,strongly disagree
7,2024-06-09 02:07:35.201864,2058-07-19 00:42:30,893.373673,9.859781,NaN,False,true,TRUE,TRUE,True,Iguana,strongly agree
8,2022-10-06 20:20:58.201864,2031-10-10 13:15:14,145.758175,NaN,NaN,False,true,TRUE,TRUE,True,Cat,strongly agree
9,2021-03-14 01:00:35.201864,2070-12-23 00:53:01,172.357125,89.465236,NaN,True,true,FALSE,False,True,Cat,disagree
10,2024-03-22 05:15:07.201864,2077-09-01 15:44:50,636.454160,NaN,NaN,True,false,TRUE,False,True,Cat,agree
11,2021-10-16 22:24:52.201864,2082-06-13 19:30:25,679.872562,NaN,NaN,True,false,FALSE,False,False,Dog,strongly agree
12,2021-05-31 21:53:03.201864,2065-03-28 15:34:19,1053.189324,18.143415,NaN,False,true,TRUE,False,False,Iguana,disagree
13,2021-02-02 14:34:21.201864,2044-03-15 13:25:45,452.020906,80.563623,NaN,True,false,FALSE,True,True,Cat,neither agree nor disagree
14,2021-09-27 05:11:45.201864,2030-10-26 07:42:07,754.776938,16.812830,NaN,True,false,TRUE,TRUE,False,Dog,strongly agree
15,2023-02-02 03:39:40.201864,2009-10-13 05:33:33,203.623115,NaN,NaN,True,false,FALSE,TRUE,False,Mouse,agree
16,2021-01-13 21:21:14.201864,2079-08-01 02:51:04,672.364268,83.465765,49.227633,True,false,FALSE,True,True,Cat,strongly disagree
17,2023-05-11 17:45:15.201864,2048-12-25 17:11:20,928.263185,18.796261,NaN,True,false,FALSE,False,False,Mouse,strongly agree
18,2023-05-31 10:58:22.201864,2084-05-12 06:36:39,498.429783,NaN,NaN,False,true,FALSE,False,False,Dog,neither agree nor disagree
19,2021-07-30 01:32:24.201864,2073-11-04 17:32:22,30.436490,37.412656,NaN,False,false,TRUE,TRUE,True,Cat,agree
20,2024-01-23 01:35:46.201864,2025-01-29 22:23:25,158.274790,83.514216,NaN,False,false,TRUE,TRUE,True,Dog,strongly agree
21,2024-01-03 08:22:39.201864,2035-08-07 11:27:42,1058.265059,16.786129,NaN,True,false,FALSE,False,False,Iguana,disagree
22,2022-03-03 22:56:41.201864,2057-08-03 19:09:23,545.743983,48.473979,NaN,True,true,TRUE,False,True,Dog,neither agree nor disagree
23,2019-05-13 15:34:37.201864,2011-09-11 16:39:47,350.124783,99.107480,NaN,True,false,TRUE,True,False,Cat,strongly agree
24,2023-04-22 00:32:08.201864,2061-05-31 17:21:51,335.637355,NaN,NaN,True,false,TRUE,True,True,Iguana,strongly disagree
25,2020-06-10 23:56:57.201864,2017-06-07 01:58:29,301.080765,70.203284,NaN,False,true,FALSE,TRUE,True,Cat,neither agree nor disagree
26,2022-08-28 09:54:44.201864,2064-04-13 10:01:12,1144.888263,52.681602,NaN,True,false,TRUE,False,True,Cat,disagree
27,2024-06-28 19:20:42.201864,2001-03-06 03:35:30,156.487673,59.996265,NaN,False,false,FALSE,False,True,Dog,strongly agree
28,2020-12-25 04:08:07.201864,2059-07-03 06:15:37,213.061279,NaN,NaN,True,false,TRUE,TRUE,False,Dog,agree
29,2023-10-16 11:30:11.201864,2066-03-12 21:07:26,1076.178307,NaN,NaN,True,false,TRUE,False,True,Mouse,strongly agree
...,...,...,...,...,...,...,...,...,...,...,...,...
70,2020-03-24 03:04:29.201864,2086-04-10 17:42:53,815.064017,NaN,NaN,True,false,FALSE,True,False,Cat,agree
71,2022-06-10 13:02:16.201864,2093-12-03 14:07:49,29.151110,68.021756,NaN,True,true,TRUE,False,False,Cat,strongly disagree
72,2023-07-09 21:24:36.201864,2000-03-21 22:02:23,1083.432988,NaN,NaN,False,false,FALSE,False,False,Cat,agree
73,2019-12-16 12:58:54.201864,2042-04-17 02:19:31,485.671281,8.359522,NaN,False,true,FALSE,False,True,Dog,disagree
74,2022-10-26 13:34:05.201864,2037-07-05 22:33:56,516.258744,23.094425,NaN,False,false,FALSE,False,True,Mouse,strongly disagree
75,2021-08-18 18:45:31.201864,2075-10-04 04:38:36,107.794211,NaN,NaN,False,false,FALSE,False,True,Mouse,strongly agree
76,2021-07-10 08:19:17.201864,2026-12-29 09:29:39,353.227691,28.193732,NaN,False,false,TRUE,False,False,Cat,strongly disagree
77,2020-12-05 10:55:00.201864,2040-05-18 15:13:17,3.232203,1.426566,NaN,False,false,TRUE,TRUE,True,Dog,agree
78,2022-09-17 03:07:51.201864,2006-11-30 12:54:12,817.986531,85.248711,NaN,False,true,TRUE,False,False,Iguana,agree
79,2023-11-05 04:43:18.201864,2018-05-22 07:31:36,1004.714344,9.086908,NaN,False,true,TRUE,TRUE,True,Iguana,agree
80,2019-06-02 08:47:44.201864,2023-03-03 11:17:11,730.671814,64.662075,NaN,False,false,TRUE,TRUE,False,Iguana,strongly agree
81,2022-07-19 23:28:30.201864,2039-06-04 09:40:10,654.740105,69.837866,NaN,True,true,TRUE,TRUE,False,Cat,disagree
82,2021-05-12 04:39:56.201864,2048-01-11 11:38:13,609.788467,NaN,NaN,True,false,FALSE,TRUE,False,Dog,neither agree nor disagree
83,2021-12-15 02:04:13.201864,2022-03-19 05:44:04,968.503235,NaN,NaN,False,false,FALSE,False,False,Cat,disagree
84,2023-06-20 04:11:29.201864,2036-07-21 17:00:49,478.857503,NaN,NaN,False,false,TRUE,False,False,Dog,disagree
85,2022-02-12 05:43:34.201864,2005-12-16 07:21:05,556.590134,NaN,NaN,True,true,TRUE,False,False,Iguana,disagree
86,2019-10-18 09:19:33.201864,2016-06-22 20:25:22,164.924221,88.145881,NaN,True,false,TRUE,False,True,Dog,disagree
87,2023-09-26 18:17:04.201864,2063-04-30 04:28:05,391.175579,55.835258,NaN,True,false,FALSE,False,True,Mouse,strongly agree
88,2024-08-07 05:46:56.201864,2069-01-23 13:46:47,1045.196720,NaN,NaN,False,false,TRUE,True,True,Cat,disagree
89,2023-09-07 01:03:57.201864,2071-12-07 06:26:08,465.294606,NaN,NaN,False,false,TRUE,False,False,Iguana,disagree
90,2023-12-14 15:09:32.201864,2068-02-09 08:13:40,446.390388,96.404287,NaN,True,false,FALSE,TRUE,True,Mouse,agree
91,2020-10-27 00:28:46.201864,2038-06-20 04:07:03,707.219151,NaN,81.644772,False,true,TRUE,False,False,Mouse,neither agree nor disagree
92,2020-02-13 16:38:15.201864,2091-01-20 21:28:28,648.919327,50.752874,NaN,False,false,TRUE,False,False,Dog,agree
93,2024-09-15 16:13:10.201864,2005-01-01 01:47:58,1052.722244,NaN,NaN,True,false,TRUE,False,True,Dog,neither agree nor disagree
94,2021-11-25 08:51:06.201864,2004-01-17 20:14:51,46.781918,NaN,32.893944,False,true,TRUE,True,False,Mouse,agree
95,2024-04-10 22:28:14.201864,2043-04-01 07:52:38,80.461233,41.410205,70.949646,False,true,FALSE,False,False,Iguana,agree
96,2020-05-22 06:43:50.201864,2080-07-15 08:24:11,912.657073,12.709115,NaN,True,true,TRUE,TRUE,False,Mouse,strongly agree
97,2019-07-11 19:13:58.201864,2072-11-20 11:59:15,777.972190,33.334909,91.122197,False,false,FALSE,False,False,Cat,strongly disagree
98,2022-11-15 06:47:12.201864,2050-11-24 04:17:34,494.560337,52.957398,NaN,True,false,FALSE,TRUE,False,Mouse,disagree
99,2019-09-08 22:53:19.201864,2012-08-25 22:12:54,711.120516,NaN,NaN,False,true,FALSE,True,False,Cat,strongly disagree